### ISSUE TITLE
changedomain.sh is not working with "./"

### ISSUE THREAD

**Issue by austrocoin** [btcpayserver/btcpayserver-azure#1]
For changing domain script DONT use "./" like in video - without it works: 

changedomain.sh subdomain.mydomain.com﻿

**Comment by NicolasDorier** [comment]
I added instructions on  https://github.com/btcpayserver/btcpayserver-azure/blob/master/README.md
Actually the best is `. changedomain.sh subdomain.mydomain.com﻿` . The . make sure your variable are updated in your current session as well.
