### ISSUE TITLE
Automatic deploy does not work for Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by hubiktomas** [btcpayserver/btcpayserver-azure#2]
When using the Deploy to Azure and selecting Ubuntu OS Version 18.04 LTS in the form, the deployment ends successfully, but the resulting virtual machine does not have all the applications configured - there is no bitcoin and litecoin daemon, no nginx. It looks like clean Ubuntu.

**Comment by NicolasDorier** [comment]
Try opening the browser, you'll see it works.
It is using docker-compose. (run `docker ps` to see your containers)

**Comment by hubiktomas** [comment]
I cannot see any process listening on HTTP/HTTPS ports and docker is not installed on the virtual machine. I am comparing deploy with Ubuntu 16.04 and 18.04 - they are different. 16.04 works, has bitcoin and litecoin daemon, nginx etc. 18.04 looks clean.

**Comment by NicolasDorier** [comment]
I will check that now

**Comment by hubiktomas** [comment]
Perfect, thank you. I am available for some debugging/logs etc. Just let me know.

**Comment by NicolasDorier** [comment]
You can come on http://slack.forkbitpay.ninja it is better for real time debug :p

**Comment by NicolasDorier** [comment]
Should be fixed by https://github.com/btcpayserver/btcpayserver-azure/commit/6f2211c8f433b398343ee5ecc73897a6374702f8 let me know.

**Comment by NicolasDorier** [comment]
Closing this as you reported it worked on slack :)
